/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdownButton: typeof import('ant-design-vue/es')['DropdownButton']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    DropdownGames: typeof import('./../components/dropdown-games.vue')['default']
    Greet: typeof import('./../components/Greet.vue')['default']
    Home: typeof import('./../pages/home/index.vue')['default']
    'IconIc:sharpAddCircleOutline': typeof import('~icons/ic/sharp-add-circle-outline')['default']
    'IconIc:sharpRemoveCircleOutline': typeof import('~icons/ic/sharp-remove-circle-outline')['default']
    MidiReader: typeof import('./../components/midi-reader.vue')['default']
    MidiReaderDropdown: typeof import('./../components/midi-reader-dropdown.vue')['default']
    MidiReaderMt3: typeof import('./../components/midi-reader-mt3.vue')['default']
    QuickLinks: typeof import('./../pages/quick-links/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./../components/upload.vue')['default']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
  }
}
