/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Greet: typeof import('./../components/Greet.vue')['default']
    MidiReaderMt3: typeof import('./../components/midi-reader-mt3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./../components/upload.vue')['default']
  }
}
